name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build-ckbNodeBridge
        run: make build-ckbNodeBridge

      - name: build-miner
        run: make build-miner

      - name: Run test
        run: make test
